package config

const USERNAME = "USERNAME_HERE"
const PASSWORD = "PASSWORD_HERE"
const PHONE_NUMBER = "PHONE#_HERE"
const TWILIO_API_KEY = "API_KEY_HERE"
const TWILIO_API_URL = "API_URL_HERE"
const DISCORD_WEBHOOK_URL = "WEBHOOK_URL_HERE"

// REPLACE PHONE NUMBER AND MESSAGE IN EXAMPLE REQUEST BODY
// WITH %S TO ALLOW FOR fmt.Sprintf TO FORMAT THEM!!!!
const TWIOLIO_REQUEST_BODY = "TWIOLIO_REQUEST_BODY_HEREnumber=%sbody=%s"
